### ISSUE TITLE
documentation for ctest runs

### ISSUE THREAD

**Issue by carns** [mercury-hpc/fabtsuite#17]
If I understand correctly, there is a mode of operation in which you execute a single script (on a login node?) and it submits multiple scheduler jobs and reports the results from each.  Is this mode documented yet?

Browsing the various .md files in the doc/ directory I'm not exactly sure where to start.

**Comment by hyoklee** [comment]
It is still in [my fork](https://github.com/hyoklee/fabtsuite) to fix some issues.

**Comment by hyoklee** [comment]
PR #18 has an updated instruction on CTest in  [doc/building_cmake.md](../blob/main/doc/building_cmake.md)
