### ISSUE TITLE
Clean up LICENSE and COPYING.

### ISSUE THREAD

**Issue by hyoklee** [mercury-hpc/fabtsuite#3]
* hlog COPYING is missing. Check if https://github.com/gnuoyd/hlog/blob/main/COPYING can be used for the ECP project.
* LICENSE doesn't match https://github.com/mercury-hpc/mercury/blob/master/LICENSE.txt.

E.g.,
```
Copyright (c) 2021, Mercury
```

**Comment by hyoklee** [comment]
I updated LICENSE file. 
https://github.com/mercury-hpc/fabtsuite/commit/fdab8b0ed92920b30354e358ddc33356e1def525

**Comment by carns** [comment]
Our preference is for a clean BSD 3 Clause license.  It can follow the example of the Mercury license https://github.com/mercury-hpc/mercury/blob/master/LICENSE.txt, with the copyright line set to `Copyright (c) 2022, UChicago Argonne, LLC and The HDF Group.`

**Comment by carns** [comment]
Oh I see.  This is the 2 clause / simplified BSD license right?  If so, that is fine for that code; they are compatible.  I would still prefer that the specific hlog license and copyright apply only to the hlog code, and that the project as a whole (the newly written code) have 3 clause with copyright assigned to UChicago and THG.

Could we just make the hlog code a git submodule, or are there modifications here?  It doesn't matter much from a licensing point of view as long as that subdir has its own license text if it's committed directly in the repo, but it might be nicer for maintenance in general to be clear where that code came from and how to update it when needed.

**Comment by hyoklee** [comment]
I think submodule will not work since I added a CMake support to hlog:

https://github.com/mercury-hpc/fabtsuite/blob/main/hlog/CMakeLists.txt

I'll add COPYING into hlog since hlog codes mention it in the comment block and close the ticket.

**Comment by carns** [comment]
Great, thanks @hyoklee
