### ISSUE TITLE
clean up executable installation

### ISSUE THREAD

**Issue by carns** [mercury-hpc/fabtsuite#4]
The spack package for fabtsuite (https://github.com/mochi-hpc/mochi-spack-packages/tree/main/packages/fabtsuite) places executables in subdirectories of the install prefix that are difficult to find, because spack packages are intentionally installed to unique locations.

It would be simpler if the commands that users should run were placed in a bin subdirectory (either in the spack package, or maybe more straightforward to do generically in the main repository).

This would also be a good time to think about the names of the executables.  It might make sense to prepend a name to the commands that associates them clearly with this test suite ("fput" and "fget" are kind of generic).

**Comment by hyoklee** [comment]
@carns , we want to rename fput/fget. Here are a few candidates that we came up with:

1. fabtget / fabtput
2. ftget / ftput
3. fi_get / fi_put

The option 3. follows the convention of bin/ programs of libfabric [1].
Which option do you like most?

[1]  https://github.com/ofiwg/libfabric/blob/main/Makefile.am

**Comment by carns** [comment]
Thanks @hyoklee .  I would vote against 3, because that seems problematic for it to sound like part of the upstream libfabric package.  The others are fine.  Thanks!

**Comment by hyoklee** [comment]
OK. I'll use 1 then.
